version: "3"
services:
  backend:
    build:
      context: backend
    environment:
      DB_TABLENAME: Idea-centered-inquiry #<DB_TABLENAME>
      DB_USERNAME: wulab #<USERNAME>
      DB_USERPSW: ytwu35415 #<USERPSW>
      DB_HOST: db
      NODE_ENV: production
    restart: always
    volumes:
      - "./uploads:/app/uploads/"
    ports:
        - "8000:8000"
    depends_on:
        - db

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: Idea-centered-inquiry #<DB_TABLENAME> 
      POSTGRES_USER: wulab #<USERNAME> 
      POSTGRES_PASSWORD: ytwu35415 #<USERPSW> 
      PGDATA: /var/lib/postgresql/data

    volumes:
      - "./db_data:/var/lib/postgresql/data"
    ports:
        - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7.5
    user: root
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: "False"
    depends_on:
      - db

  frontend:
    build: 
      context: frontend
    ports:
      - '80:3000'
    stdin_open: true
    restart: always
    volumes:
      - "./frontend/src:/app/src"
    depends_on:
      - backend
      - websocket-srv
    environment:
      # Fixes bug where websocket connection is fixed to default port 3000
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
  websocket-srv:
    build:
      context: socketio-server
    environment:
      LOG_LEVEL: info
    restart: always
    ports:
        - "3030:3030"
volumes:
    db_data:
    pgadmin_data:

networks:
  frontend:
  backend:
